- name: Deploy Docker image to Kubernetes
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure python3, python3-pip and python3-kubernetes are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-kubernetes
        state: present

    - name: Ensure .kube directory exists
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy kubeconfig to target node
      copy:
        src: /home/ansadmin/.kube/config
        dest: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    - name: Apply Kubernetes manifest
      kubernetes.core.k8s:
        kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
        state: present
        definition: "{{ lookup('file', 'kubernetesfile.yml') }}"
