- name: Deploy Docker image to Kubernetes
  hosts: all
  tasks:
    - name: Apply Kubernetes manifest
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        definition: "{{ lookup('file', 'kubernetesfile.yml') }}"
