---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcare
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcare
  template:
    metadata:
      labels:
        app: hcare
    spec:
      containers:
        - name: hcare
          image: jayasurya0199/staragilehcarev1:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: hcare
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: hcare
